NergyCertificate/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NergyCertificate.Framework;
using NergyCertificate.Framework.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NergyCertificate.Controllers
{
    public class CourseController : Controller
    {
        private readonly NergyCertDbContext _context;
        public CourseController(NergyCertDbContext Context)
        {
            _context = Context;
        }

        //course Index
        public IActionResult Index()
        {

            var course = _context.Courses
                .Include(p => p.Batch)
                .ThenInclude(p => p.User)
                .ToList();
            return View(course);
        }

        //course Create

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.bacthlist = new SelectList(_context.Batches, "BatchId", "BatchName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Course course)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    
                    _context.Add(course);
                    await _context.SaveChangesAsync();

                    TempData["Success"] = "course is created successfully";
                    return RedirectToAction("Index", "course");
                }
                return View(course);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(course);
            }

        }


        //course Edit


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Course course)
        {
            if (id != course.CourseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "course is updated successfully";
                }

                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(course);
                }
                return RedirectToAction("Index", "course");


            }

            return View(course);
        }


        //course Delete
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var course = await _context.Courses.FindAsync(id);

                if (course == null)
                {
                    return NotFound();
                }
                _context.Courses.Remove(course);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Category is deleted successfully";
            }
            catch (Exception ex)
            {
                if (ex.Message.Contains("Conflict"))
                    TempData["Error"] = "Unable to delete, please make sure that there are no sub-categories in it";
                else
                    TempData["Error"] = "An error has occured while deleting the item";
            }

            return RedirectToAction("Index", "course");
        }
    }

}

NergyCertificate/Views/Course/Create.cshtml
@model NergyCertificate.Framework.Domain.Course

@{
    ViewData["Title"] = "Courses";
}


<section class="section">
    <div class="section-header">
        <h1>Courses</h1>

    </div>
    <div class="section-body">
        <h2 class="section-title">Courses</h2>
        <p class="section-lead"> Create Courses</p>
        <form asp-action="Create" enctype="multipart/form-data">
            <div class="card">

                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">

                        <div class="form-group col-md-4">
                            <label asp-for="BatchId" class="control-label"></label>
                            <select asp-for="BatchId" class="form-control select2" asp-items="ViewBag.bacthlist"><option selected value="">None</option></select>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="CourseName" class="control-label"></label>
                            <input asp-for="CourseName" class="form-control" />
                            <span asp-validation-for="CourseName" class="text-danger"></span>
                        </div>

                        <div class="form-group col-md-4">
                            <label asp-for="CourseDescription" class="control-label"></label>
                            <input asp-for="CourseDescription" class="form-control" />
                            <span asp-validation-for="CourseDescription" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-whitesmoke">
                    <input type="submit" value="Create" class="btn btn-primary float-left" />
                </div>
            </div>
        </form>
    </div>
</section>

NergyCertificate/Views/Course/Edit.cshtml
@model NergyCertificate.Framework.Domain.Course

@{
    ViewData["Title"] = "Courses";
}


<section class="section">
    <div class="section-header">
        <h1>Courses</h1>

    </div>
    <div class="section-body">
        <h2 class="section-title">Courses</h2>
        <p class="section-lead"> Edit Courses</p>
        <form asp-action="Edit" enctype="multipart/form-data">
            <div class="card">

                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <input type="hidden" asp-for="@Model.CourseId" />
                        <input type="hidden" asp-for="@Model.BatchId" />
                        <div class="form-group col-md-4">
                            <label asp-for="CourseName" class="control-label"></label>
                            <input asp-for="CourseName" class="form-control" />
                            <span asp-validation-for="CourseName" class="text-danger"></span>
                        </div>

                        <div class="form-group col-md-4">
                            <label asp-for="CourseDescription" class="control-label"></label>
                            <input asp-for="CourseDescription" class="form-control" />
                            <span asp-validation-for="CourseDescription" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-whitesmoke">
                    <input type="submit" value="Update" class="btn btn-primary float-left" />
                </div>
            </div>
        </form>
    </div>
</section>

NergyCertificate/Views/Course/Index.cshtml
@model IEnumerable<NergyCertificate.Framework.Domain.Course>

@{
    ViewData["Title"] = "Courses";
}


<section class="section">
    <div class="section-header">
        <h1>Batches</h1>

    </div>
    <div class="section-body">
        <h2 class="section-title">Courses</h2>
        <p class="section-lead"> Manage Groups or Courses</p>
        <div class="card">

            <div class="card-body">
                @if (TempData["Success"] != null)
                {
                    <div class="alert alert-success alert-dismissible show fade">
                        <div class="alert-body">
                            <button class="close" data-dismiss="alert">
                                <span>×</span>
                            </button>
                            @TempData["Success"]
                        </div>
                    </div>
                }
                else if (TempData["Error"] != null)
                {
                    <div class="alert alert-dark alert-dismissible show fade">
                        <div class="alert-body">
                            <button class="close" data-dismiss="alert">
                                <span>×</span>
                            </button>
                            @TempData["Error"]
                        </div>
                    </div>
                }

                <p>
                    <a asp-controller="Course" asp-action="Create" class="btn btn-primary">Create New</a>
                </p>

                <div class="table-responsive">
                    <table class="table table-striped" width="100%" id="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.CourseName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CourseDescription)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Batch.BatchName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Batch.User.Name)
                                </th>



                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(c => item.CourseName)
                                </td>
                                <td>
                                    @Html.DisplayFor(c => item.CourseDescription)
                                </td>
                                <td>
                                    @Html.DisplayFor(c => item.Batch.BatchName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Batch.User.Name)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-controller="Course" class="btn btn-outline-primary" asp-route-id="@item.CourseId">Edit</a>

                                    <a asp-action="Delete" asp-controller="Course" class="btn btn-outline-danger delete" asp-route-id="@item.CourseId">Delete</a>
                                </td>


                            </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    <script type="text/javascript">
    $(document).ready(function () {
             $('.table').on('click', '.delete', function (e, data) {
                 if (!data) {
                     handleDelete(e, 1);
                 } else {
                     window.location = $(this).attr('href');
                 }
             });
         });
         function handleDelete(e, stop) {
             if (stop) {
                 e.preventDefault();
                 swal({
                     title: "Are you sure?",
                     text: "You will not be able to recover it again!",
                     icon: "warning",
                     buttons: true,
                     dangerMode: true,
                     closeOnConfirm: false
                 }).then((willDelete) => {
                     if (willDelete) {
                        $(e.target).trigger('click', {});
                     } else {
                     }
                 });
             }
         };
    </script>
}